- package.json
- src/components/hero/component.js
- src/utils/carto-api.js
- yarn.lock
Populating countries dropdown.
Browse to the country page. The dropdown should be populated by data in Carto tables.
https://www.pivotaltracker.com/story/show/172326825
> Connected countries with data in carto

- package.json
- src/components/chart/bar/component.js
- src/components/chart/bar/constants.js
- src/components/chart/bar/index.js
- src/components/widget/component.js
- src/components/widget/styles.scss
- src/components/widget/utils.js
- yarn.lock
⚠️ Before submitting the PR, make sure:
- You asked someone to review it
- You chose a meaningful title
---
What to test? How to do it?
Link to the task(s), if any
> working with fake data on widgets

- src/components/card/component.js
- src/components/widget/widget-templates/stacked-bars/component.js
- src/components/widgets/component.js
- src/components/widgets/index.js
- src/components/widgets/styles.scss
- src/pages/country/category/health.js
- src/pages/country/category/migration.js
- src/pages/country/category/summary.js
- src/pages/country/constants.js
This PR includes component Widgets to filter widgets by category for different tabs.
Just healthcare access implemented
Go to health tab you should be able to see the widget but not in the rest of the tabs
http://localhost:3000/country/NGA/healthcare-access
https://www.pivotaltracker.com/story/show/172286998
> widgets component filtering categories

- src/components/chart/line/component.js
- src/components/chart/line/constants.js
- src/components/chart/line/index.js
- src/components/widget/component.js
Created a new chart for spark line widgets.
What to test? How to do it?
Link to the task(s), if any
> added line chart

- package.json
- src/components/chart/bar/component.js
- src/components/chart/bar/constants.js
- src/components/widget/component.js
- src/components/widget/utils.js
- src/components/widgets/component.js
⚠️ Before submitting the PR, make sure:
- You asked someone to review it
- You chose a meaningful title
---
What to test? How to do it?
Link to the task(s), if any
> connected widget with data

- src/components/card/component.js
- src/data/widgets.json
- src/pages/country/category/politics.js
- src/pages/country/category/summary.js
- src/pages/country/constants.js
Livelihood widgets added to widgets.json
Go to politics tab to check (to be adapted once all categories get defined)
https://www.pivotaltracker.com/story/show/172402202
> livelihood cat to widgets.json

- src/data/widgets.json
Financial lives added to widgets.json
http://localhost:3000/country/ZAF/financial_lives 
Go to politics tab to see widgets
https://www.pivotaltracker.com/story/show/172402202
> financial lives cat to widgets.json

- package.json
- src/components/chart/bar/constants.js
- src/components/widget/utils.js
- src/services/indicators.js
- src/utils/dates.js
- src/utils/strings.js
- yarn.lock
* Format for X and Y axis.
* Showing percentage instead value.
* Filter NaN and N/A values.
> Widgets data, format and filters

- src/components/filters/component.js
- src/modules/filters/initial-state.js
This PR saves filters in an array in redux
> filters results to array

- src/components/navigation/component.js
- src/components/navigation/styles.scss
- src/pages/country/styles.scss
> nav styles

- package.json
- src/components/download/components.js
- src/components/download/index.js
- src/components/header/component.js
- src/components/header/styles.scss
- src/services/data.js
- yarn.lock
Component download data added
Country page, button download data
https://www.pivotaltracker.com/story/show/172472206
> download data component

- public/index.html
- src/components/card/component.js
- src/components/dropdown/styles.scss
- src/components/filters/component.js
- src/components/filters/styles.scss
- src/components/header/component.js
- src/components/header/styles.scss
- src/components/hero/styles.scss
- src/components/share/component.js
- src/components/subscribe/component.js
- src/components/subscribe/index.js
- src/components/subscribe/styles.scss
- src/components/summary/component.js
- src/components/widget/component.js
- src/components/widget/styles.scss
- src/pages/country/styles.scss
- src/styles/_settings.scss
- src/styles/index.scss
This PR add component Subscribe
- No feedback added because it has a default one.
- Title added to all modals, prevent close button to go left.
- Arrows added to dropdowns
- Widgets title size changed
- Couple of media queris added 
All changes made in country page (subscribe at the top of the page)
https://www.pivotaltracker.com/story/show/172472213
Link to the task(s), if any
> subscribe + general styles

- src/components/filters/component.js
> Fixed reset filters button

- src/components/button/component.js
- src/components/card/component.js
- src/components/chart/bar/utils.js
- src/components/modal/component.js
- src/components/navigation/component.js
- src/components/navigation/styles.scss
- src/components/summary/component.js
- src/components/widget/component.js
- src/components/widget/styles.scss
- src/components/widgets/styles.scss
- src/pages/country/component.js
- src/pages/country/styles.scss
- src/services/categories.js
- src/styles/_base.scss
- src/styles/_settings.scss
- src/styles/index.scss
Styles for country page and widgets list
> styles for widgets

- src/components/subscribe/component.js
- src/components/subscribe/styles.scss
This PR adds new form in Subscribe component (country included)
Open subscribe modal
https://www.pivotaltracker.com/story/show/172495525
> iso added to subscribbe

- src/components/filters/constants.js
Update name of columns in filters constants
https://www.pivotaltracker.com/story/show/172529029
> columns in filters updated

- src/components/filters/constants.js
New labels and values for filters
https://www.pivotaltracker.com/story/show/172402082
> filters new values

- public/index.html
- src/components/download-form/component.js
- src/components/download-form/index.js
- src/components/download-form/styles.scss
- src/components/header/component.js
- src/styles/index.scss
This PR adds new form to download data (and removes old component from header)
https://www.pivotaltracker.com/story/show/172558935
> new download through typeform

- src/components/navigation/component.js
- src/components/navigation/styles.scss
- src/pages/country/styles.scss
Margin bottom added to navigation to prevent box-shadow to get cut
https://www.pivotaltracker.com/story/show/172578985
> margin to navigation

- src/components/widget/component.js
- src/components/widgets/component.js
This PR calculates active filters in a widget
> active filters in widget

- src/components/filters/component.js
- src/components/navigation/styles.scss
- src/components/share/component.js
- src/components/share/index.js
filters added to url when sharing a widget
margin removed in navigation bar
click share in any widget
https://www.pivotaltracker.com/story/show/172575625
> filters to url share

- src/components/chart/bar/component.js
Fixing responsive for small screens in multiple bars charts.
> fixing responsive for widgets

- public/resources.html
- src/pages/resources/component.js
I don't like so much this solution, I expected a HTML, not CSS and JS.
> I dont proud of this iframe, lets think in other solution

- src/components/header/styles.scss
> header resize

- src/components/filters/component.js
- src/components/filters/constants.js
- src/components/filters/index.js
- src/services/filters.js
Filters working dynamically
Open filters
https://www.pivotaltracker.com/story/show/172605039
> new filter region

- src/components/widgets/component.js
- src/pages/widget/component.js
This PR adds a new condition to show just specific widgets in each country
Check if filters in different countries match with what it should be
https://www.pivotaltracker.com/story/show/172650048
> filter widgets by country

- src/components/dropdown/component.js
- src/components/navigation/component.js
- src/components/subscribe/styles.scss
- extra margin removed from subscribe component
- categories dropdown closes on clicking link
country page:
- check gap between buttons
- categories dropdown on Click on category
> small bugs

- public/index.html
- src/index.js
This PR initialises google analytics in app
Check google analytics
https://www.pivotaltracker.com/story/show/172558843
> analytics initialize

- public/index.html
- src/components/dropdown/component.js
- src/components/dropdown/index.js
- src/components/navigation/component.js
- src/components/navigation/index.js
- src/components/summary/component.js
- src/components/summary/index.js
- src/pages/home/component.js
- src/pages/home/index.js
google analytics events removed
> script back in analytics

- src/components/chart/bar/component.js
- src/components/chart/bar/utils.js
This PR adds a **SHORT TERM** solution to labels repeated in x Axis for multiple stacked bar charts. It prevents to have repeated values (quick solution in order to not invest time in something may change next, week, task added to PT to look into this next week https://www.pivotaltracker.com/story/show/172675635)
Check xAxis in multiple stacked bar charts.
https://www.pivotaltracker.com/story/show/172575524
> TempSolution: label in xAxis

- src/components/disclaimer/component.js
- src/components/disclaimer/constants.js
- src/components/disclaimer/index.js
- src/components/disclaimer/styles.scss
- src/components/header/component.js
- src/components/header/styles.scss
- src/pages/home/styles.scss
- src/styles/index.scss
Disclaimer added to the top of the header
> disclaimer component

- public/indicators.html
- src/components/header/component.js
- src/components/hero/component.js
- src/components/page-switch/component.js
- src/components/page-switch/index.js
- src/config/router.js
- src/modules/page/reducer.js
- src/pages/component.js
- src/pages/indicators/component.js
- src/pages/indicators/index.js
- src/pages/indicators/styles.scss
- src/styles/index.scss
New indicators page added to the project (currently with resources content duplicated).
Navigation bar added to home page as requested.
What to test? How to do it?
Check if buttons appear in home page.
Check hero in all pages.
> indicators page

- src/components/navigation/component.js
- src/components/summary/component.js
- src/pages/country/component.js
Summary added to dropdown
https://www.pivotaltracker.com/story/show/172716319
> summaries in dropdown added

- src/components/header/component.js
- src/pages/home/styles.scss
This PR fixes broken button in home page
> home styles fixes

- src/data/widgets.json
- src/styles/_recharts.scss
This PR prevents chart to have different highs.
- It sets a min height to legend to force legends of one or two lines to have same height.
- It position in larger legends to
> min-height in legend

- public/indicators-content.html
- src/data/widgets.json
> Deploy to production
